[package]
name = "png-afl"
version = "0.2.0"
authors = ["Sergey Davidoff <shnatsel@gmail.com>", "Paul Grandperrin <paul.grandperrin@gmail.com>"]
edition = "2018"

[dependencies]
afl = "0.4.3"
png = { path = "../" }
